use dispatchdatabase;
SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE companyconfigchannelmaster;
DROP TABLE companyconfigeventtypemaster;
DROP TABLE companyfieldlabelconfiguration;
DROP TABLE companygroupmaster;
DROP TABLE companymenumaster;
DROP TABLE companypackinglevelmaster;
DROP TABLE companysubmenumaster;
DROP TABLE countryskumapping;
DROP TABLE datatemplatemaster;
DROP TABLE dateformatmaster;
DROP TABLE devicemaster;
DROP TABLE emaileventmaster;
DROP TABLE emailkeywords;
DROP TABLE emailsettings;
DROP TABLE emailtemplatemaster;
DROP TABLE emailtemplateuserlist;
DROP TABLE errorlogmaster;
DROP TABLE fieldmaster;
DROP TABLE globalcompanymaster;
DROP TABLE heterobatchmaster;
DROP TABLE heteroparentchild;
DROP TABLE heteroproductlist;
DROP TABLE heteroproductmaster;
DROP TABLE labelconfigmaster;
DROP TABLE labelmaster;
DROP TABLE linemaster;
DROP TABLE mappinglevelmaster;
DROP TABLE mappingmaster;
DROP TABLE notificationdetails;
DROP TABLE notificationmaster;
DROP TABLE packinglevelmaster;
DROP TABLE parameterdetails;
DROP TABLE partymaster;
DROP TABLE partyplantcompanymaster;
DROP TABLE plantmaster;
DROP TABLE poolrsngeneration;
DROP TABLE poolssccgeneration;
DROP TABLE productmappingmaster;
DROP TABLE regulatorycompanymapping;
DROP TABLE regulatorymaster;
DROP TABLE rolemaster;
DROP TABLE rsnserializationtemplatemaster;
DROP TABLE scpconfiguration;
DROP TABLE serailzationtemplatelist;
DROP TABLE scpmasteroutwardlist;
DROP TABLE scpmastersameleveloutwardlist;
DROP TABLE serializationtemplateparameterdetails;
DROP TABLE serializationtemplateplantmapping;
DROP TABLE skuformatmaster;
DROP TABLE sscctemplatemaster;
DROP TABLE strolemaster;
DROP TABLE submenumaster;
DROP TABLE systemconfiguration;
DROP TABLE templatelist;
DROP TABLE templatemaster;
DROP TABLE userplantlinemaster;
DROP TABLE widgets;


SET FOREIGN_KEY_CHECKS = 1;
SET SQL_SAFE_UPDATES = 1;
