use dispatch;
SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE audittrail;
TRUNCATE TABLE audittransaction;
TRUNCATE TABLE batchlist;
TRUNCATE TABLE batchmaster;
TRUNCATE TABLE companyitpolicymaster;
TRUNCATE TABLE companymaster;
TRUNCATE TABLE dbversion;
TRUNCATE TABLE dbversionhistory;
TRUNCATE TABLE deliverychallanlist;
TRUNCATE TABLE deliverychallanmaster;
TRUNCATE TABLE groupmaster;
TRUNCATE TABLE grouproleinfo;
TRUNCATE TABLE importrsnshipment;
TRUNCATE TABLE inventory;
TRUNCATE TABLE locationmaster;
TRUNCATE TABLE logisticcompanymaster;
TRUNCATE TABLE logisticcompanyvehiclemaster;
TRUNCATE TABLE orderlist;
TRUNCATE TABLE ordermaster;
TRUNCATE TABLE orderschememaster;
TRUNCATE TABLE ordertemplatelist;
TRUNCATE TABLE productlist;
TRUNCATE TABLE productmaster;
TRUNCATE TABLE routelist;
TRUNCATE TABLE routemaster;
TRUNCATE TABLE rsnhistoryinfo;
TRUNCATE TABLE schemefreeproductmaster;
TRUNCATE TABLE schememaster;
TRUNCATE TABLE schemeproductmaster;
TRUNCATE TABLE schemeregionmaster;
TRUNCATE TABLE schemescpmaster;
TRUNCATE TABLE scpmaster;
TRUNCATE TABLE shipmentlist;
TRUNCATE TABLE shipmentmaster;
TRUNCATE TABLE shipmentreturnlist;
TRUNCATE TABLE shipmentreturnmaster;
TRUNCATE TABLE usermaster;
TRUNCATE TABLE userpwdtransaction;
TRUNCATE TABLE userscpmaster;
SET FOREIGN_KEY_CHECKS = 1;
SET SQL_SAFE_UPDATES = 1;

